Encourage projects to write better READMEs
girder/cookiecutter-girder-4 pull request #168
Opened 2021-12-02 21:04 UTC by banesullivan

Resolve #162 

In the hopes that we will start writing more informative READMEs for Grider4 Projects based on this cookie-cutter, I have moved the overwhelming development instructions to a new `DEVELOPMENT.md` file and introduced a new README template.

This also forces users to give a one-line description of the project on creation with the `project_description` variable.

2021-12-03 15:51 UTC, subdavis commented on {{ cookiecutter.project_slug }}/README.md
> +## 🧑‍💻 Development
nit: remove🧑. It's the only line with 2 emoji so it stands out, I don't think it adds signal, and it's gendered.

2021-12-03 16:07 UTC, banesullivan commented on {{ cookiecutter.project_slug }}/README.md
> +## 🧑‍💻 Development
Huh, not sure what happened here. The second emoji wasn't rendering on my end so it slipped by. Replace with non-person emoji

2021-12-03 16:08 UTC, banesullivan commented on {{ cookiecutter.project_slug }}/README.md
> +## 🧑‍💻 Development
Re emojis. I added them because that's the mood I was in yesterday. I totally understand if we want to remove them all

2021-12-06 15:29 UTC, zachmullen requested changes

2021-12-06 15:29 UTC, zachmullen commented on {{ cookiecutter.project_slug }}/setup.py
>          long_description = f.read()
```suggestion
    with readme_file.open(encoding='utf-8') as f:
        long_description = f.read()
```

2021-12-06 15:29 UTC, zachmullen commented on {{ cookiecutter.project_slug }}/setup.py
> +from io import open as io_open
```suggestion
```

2022-07-15 20:23 UTC, closed without merging