master -> main
girder/cookiecutter-girder-4 pull request #172
Opened 2022-01-22 00:35 UTC by banesullivan

The default base branch for GitHub is now `main` the cookiecutter's workflow should reflect that.

2022-01-24 18:19 UTC, brianhelba requested changes
See comment.

2022-01-25 00:42 UTC, banesullivan commented
That doesn't seem to work: https://github.com/girder/cookiecutter-girder-4/actions/runs/1742947993

I'll change this to let the user specify the default branch in the cookie-cutter options

2022-01-25 00:47 UTC, banesullivan commented
Updated to have a new `default_branch` option, which IMO should default to `main`

2022-05-17 23:12 UTC, brianhelba commented
It seems that GitHub Actions currently lacks technical support for dynamic matching of the default branch. It must be named.

This cookiecutter (like any) requires the bootstrapping developer to run `git init` as a separate step, and they can easily select any default branch name. Deciding which specific name is best is beyond what this cookiecutter can address. Downstream projects can make their own choices, and it's easy to alter the default branch at project bootstrap.

I'll file a bug to revisit this if GitHub adds support for dynamic branch names

2022-05-17 23:12 UTC, closed without merging

2022-05-17 23:19 UTC, brianhelba commented
See https://github.com/girder/cookiecutter-girder-4/issues/188

To be clear, I'm sympathetic to projects that want to use a different Git repo structure. However, I don't want to add even more complexity to this repo by having a new cookiecutter option, unless it adds greater utility.