GitHub Workflow to publish development docker images to ghcr.io
girder/cookiecutter-girder-4 pull request #174
Opened 2022-01-22 00:47 UTC by banesullivan

Note this is based on #172

For many projects, it can be useful to have pre-built images that can be quickly pulled down to spin up a project. 

For example, if the UI/UX team is helping fix a bug or implement new front-end code, having prebuilt images that can spin up the application using the override included in `{{ cookiecutter.project_slug }}/docker-compose.override.no-build.yml` as:

```
docker compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.override.no-build.yml up
```

Will make it much faster/easier for external collaborators to spin up the application.

An additional use case is when there is a VueJS based front-end application that has a different development team than the backend Girder4 project - in these scenarios, it will also be helpful for that team to be able to pull the latest pre-built images as needed rather than building themselves.

2022-01-22 00:48 UTC, banesullivan commented on {{ cookiecutter.project_slug }}/.github/workflows/docker-package.yml
> +        docker-file: [django, ]
This is a matrix to simplify when/if the downstream project creates different images for the `celery` service, etc.

2022-01-22 00:50 UTC, banesullivan commented on {{ cookiecutter.project_slug }}/.github/workflows/docker-package.yml
> +  IMAGE_NAME: ${{ github.repository }}
It looks like jinja/cookiecutter is trying to populate these values. I'm not sure how to work around this.

2022-01-22 00:59 UTC, banesullivan commented on {{ cookiecutter.project_slug }}/.github/workflows/docker-package.yml
> +  IMAGE_NAME: ${{ github.repository }}
Nevermind, escaping these within `{{ }}` should do it

2022-02-08 00:50 UTC, brianhelba requested changes
My feeling is that this adds too much complexity for the benefit of improving image rebuild times. Even then, it's not a strict improvement, but rather a net improvement as a tradeoff between decreased CPU time and increased download time.

Running `docker-compose build django --no-cache` on a fresh cookiecutter checkout takes 90 seconds total on my laptop. I don't think that's particularly burdensome, considering it only needs to be executed once at the start of the project and then whenever dependencies change.

I am worried about additional breakages caused by the cache, since cache invalidation is generally a source of pain. Actually, the existing need to occasionally rebuild local Docker images is already a cache invalidation problem, and I'm vaguely concerned that moving to a central cache can only make it worse. Although developers can choose to not to use the central cache, that's another decision point to be figured out.

---

I think for projects with extremely long build times, the facts may be such that this is worthwhile, so I want to preserve this knowledge. Maybe a good solution is to publish this technique somewhere, and let projects adopt if their build times eventually get too long?

2022-02-08 02:10 UTC, banesullivan commented
Thanks for the thoughtful consideration, @brianhelba! In review/hindsight, I agree with your take that this adds significant complexity and is a frivolous tradeoff between CPU time and download time for most projects. For these reasons, I am closing this PR

n the case of ResonantGeoData (a project with a large dependency stack), this is a huge help - but I realize that most projects have a much lighter stack and will not gain much if any benefit from this workflow all while eating up CI execution time.

> Maybe a good solution is to publish this technique somewhere, and let projects adopt if their build times eventually get too long?

I have currently published this technique internally (I can share link internally), but I believe it would be useful to share publically as well. I have a few thoughts on where/how which we should discuss internally.

2022-02-08 02:10 UTC, closed without merging